### PR TITLE
ON HOLD - init config for CALM sites layer

### PR DESCRIPTION
**Pull request by trey-stafford**
## Description

Add Circumpolar Active Layer Monitoring (CALM) Network sites layer. It was recommended that we look at this data by [Christina Schaedel](https://www.woodwellclimate.org/staff/christina-schaedel/).

This data is provided in a few different formats: a `kml` (Google Earth format) file that does not seem to contain useful attribute information, a 7-zipped shapefile that contains useful (but incomplete/misleading) attributes, and a microsoft xls document that appears to contain all of the data.

This PR adds data from the Shapefile. It has some issues:

* It encodes missing data as 0, which could be a valid value
* Attribute names are not correct. There is a column for each year from 1990-2022 in the excel spreadsheet but in the shapefile each of these columns is named "F8" - "F32" (F8 is 1990 and F32 is 2022).
* There may be missing information about the type of measurement each record represents. The spreadsheet uses color as a label (e.g., red-highlighted records represent sites that use "spatially-oriented mechanical probing at regular intervals across a grid" while blue sites use "thaw-tube measurements".

Unfortunately the excel spreadsheet has headers/multiple sections and would probably require a Python script to completely parse out. ~~Given that there are no sites in Greenland,~~ maybe we should hold off on this layer and consider others first.

## Checklist

If an item on this list is done _or not needed_, simply check it with `[x]`.

- [ ] Config lockfile updated (`inv config.export > qgreenland/config/cfg-lock.json`)
- [ ] Version bumped if needed (`bumpversion (major|minor|patch|prerelease|build`)
- [ ] CHANGELOG.md updated
- [ ] Documentation updated if needed
- [ ] New unit tests if needed

### CODE REVIEW

**Comment by trey-stafford** [comment]
CALM_screenshot

**Comment by MattF-NSIDC** [comment]
>Unfortunately the excel spreadsheet has headers/multiple sections and would probably require a Python script to completely parse out. Given that there are no sites in Greenland, maybe we should hold off on this layer and consider others first.

I'm thinking hold off as well. We'd be adding specialist logic for something that may not have much value for our users, given there are no features in Greenland.

We could keep this PR open, maybe give it a label or milestone so we know at a glance why it'll be idling around long-term?

**Comment by trey-stafford** [comment]
Actually, there are three sites in Greenland - my initial glancing at the data w/ the default symbology wasn't good enough :sweat_smile:

**Comment by MattF-NSIDC** [comment]
Ah. Do you feel this layer will be particularly valuable? The ratio of cost:benefit I feel may still not be worth making this layer a priority because of the format issues.

**Pull request closed without merging**
